# Generated by Django 3.0.6 on 2020-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no_image.svg', upload_to='images'),
        ),
    ]
